"use strict";

const fs = require("fs");
const path = require("path");
const seedPage = require("./seed-data");

// Mint a full-access API token for the content-automation scripts and write it
// to <repo>/scripts/.env so the CLI/skills can authenticate with zero manual
// admin steps. Local-dev convenience; the file is gitignored.
async function ensureAutomationToken(strapi) {
  const repoRoot = path.join(__dirname, "..", "..");
  const scriptsDir = path.join(repoRoot, "scripts");
  const envPath = path.join(scriptsDir, ".env");
  const TOKEN_NAME = "content-automation";

  // Already wired up? leave it alone.
  if (fs.existsSync(envPath)) {
    const txt = fs.readFileSync(envPath, "utf8");
    if (/^STRAPI_API_TOKEN=.+/m.test(txt)) return;
  }

  const tokenService = strapi.service("admin::api-token");

  // Remove any stale token of the same name (its raw key is unrecoverable).
  const existing = await strapi.db
    .query("admin::api-token")
    .findOne({ where: { name: TOKEN_NAME } });
  if (existing) await tokenService.revoke(existing.id);

  const created = await tokenService.create({
    name: TOKEN_NAME,
    description: "Auto-generated for content-automation scripts",
    type: "full-access",
    lifespan: null,
  });

  const host = process.env.HOST === "0.0.0.0" ? "localhost" : process.env.HOST || "localhost";
  const port = process.env.PORT || 1337;
  const body = [
    "# Auto-generated by cms bootstrap. Gitignored. Do not commit.",
    `STRAPI_URL=http://${host}:${port}`,
    `STRAPI_API_TOKEN=${created.accessKey}`,
    "",
  ].join("\n");

  fs.mkdirSync(scriptsDir, { recursive: true });
  fs.writeFileSync(envPath, body, { mode: 0o600 });
  strapi.log.info(`Wrote automation API token to scripts/.env`);
}

// Make the Page API publicly readable (find + findOne) without manual setup.
async function grantPublicReadAccess(strapi) {
  const publicRole = await strapi.db
    .query("plugin::users-permissions.role")
    .findOne({ where: { type: "public" } });

  if (!publicRole) return;

  const actions = ["api::page.page.find", "api::page.page.findOne"];
  for (const action of actions) {
    const existing = await strapi.db
      .query("plugin::users-permissions.permission")
      .findOne({ where: { action, role: publicRole.id } });

    if (!existing) {
      await strapi.db.query("plugin::users-permissions.permission").create({
        data: { action, role: publicRole.id },
      });
    }
  }
}

// Seed one sample "talent-500" page on first boot.
async function seedSamplePage(strapi) {
  const existing = await strapi.documents("api::page.page").findMany({
    filters: { slug: seedPage.slug },
  });
  if (existing && existing.length > 0) return;

  await strapi.documents("api::page.page").create({
    data: seedPage,
    status: "published",
  });
  strapi.log.info(`Seeded sample page: /${seedPage.slug}`);
}

module.exports = {
  register() {},

  async bootstrap({ strapi }) {
    try {
      await grantPublicReadAccess(strapi);
      await seedSamplePage(strapi);
      await ensureAutomationToken(strapi);
    } catch (err) {
      strapi.log.error("Bootstrap seed failed: " + err.message);
    }
  },
};
